version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8082"
    depends_on:
      - db

  db:
    image: remote_mysql
    container_name: mysql_remote
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: inventory_management_db
    ports:
      - "3306:3306"
